version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Fracspace@2024
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
    volumes:
      - /home/administrator/.n8n:/home/node/.n8n

