version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Fracspace@2024
      - WEBHOOK_TUNNEL_URL=https://your-app-name.up.railway.app/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true 
    volumes:
      - /home/administrator/.n8n:/home/node/.n8n
    entrypoint: ["/bin/sh", "-c", "chmod 700 /home/node/.n8n/config && n8n"]
